In [ ]:
!pip install mysql-connector-python

In [ ]:
# IP
!curl ipecho.net/plain

In [ ]:
# conexão
from google.cloud import bigquery
from google.colab import auth
# Autenticar a entrada
auth.authenticate_user()

In [ ]:
import pandas as pd
import mysql.connector as mc


data = {
    'Produto': ['Arroz', 'Feijão', 'Macarrão', 'Óleo', 'Açúcar', 'Sal', 'Café', 'Leite', 'Farinha', 'Manteiga'],
    'Preço': [5.50, None, 4.20, None, 3.80, 2.00, None, 4.50, None, 6.00],
    'Quantidade': [50, None, 30, None, 40, 60, None, 45, None, 35],
    'Categoria': ['Alimentos', 'Alimentos', None, 'Alimentos', 'Alimentos', 'Alimentos', 'Bebidas', None, 'Alimentos', 'Alimentos'],
    'Fornecedor': ['Fornecedor A', None, 'Fornecedor B', 'Fornecedor A', None, 'Fornecedor C', 'Fornecedor B', None, 'Fornecedor C', 'Fornecedor A']
}

# transforma em DataFrame
df = pd.DataFrame(data)
display(df)

# Conta os nulos
print(f"Total de nulos: {df.isnull().sum().sum()}")

# Média
media_preco = df['Preço'].mean()
# print(media_preco)

# substituindo os nulos pela media_preco
df['Preço'].fillna(media_preco, inplace=True)

# Mediana
mediana_qtd = df['Quantidade'].median()
# print(mediana_qtd)

# substituindo os nulos pela mediana_qtd
df['Quantidade'].fillna(mediana_qtd, inplace=True)

# substituindo os nulos por "Desconhecido"
df['Categoria'].fillna("Desconhecido", inplace=True)

# Moda
moda_fornecedor = df['Fornecedor'].mode()[0]
#print(moda_fornecedor)

# substituindo os nulos pela moda_fornecedor
df['Fornecedor'].fillna(moda_fornecedor, inplace=True)

# Conta os nulos
print(f"Total de nulos após tratamento: {df.isnull().sum().sum()}")
display(df)

# Definição das variáveis de conexão
host = 'IP_da_VM'   # Endereço do servidor MySQL
user = 'nome_do_usuário'           # Nome de usuário do MySQL
password = 'senha_do_usuário'           # Senha do MySQL (deve ser definida para conexões seguras)
database = 'nome_da_database'    # Nome do banco de dados a ser utilizado

# Estabelecimento da conexao com o banco de dados
connection = mc.connect(
    host=host,
    user=user,
    password=password,
    database=database
)

# Criação de um cursor para executar consultas SQL
cursor = connection.cursor()

client = bigquery.Client()
# id do projeto que vc vai acessar
project_id = 'nome_código_do_projeto'
# a string é formada por project_id.dataset.tabela
table_id = f'{project_id}.eeep_soul.flight_0001'
# manda para a big query o dataframe, e caso já exista, substitui
df.to_gbq(table_id, project_id=project_id, if_exists='replace')

In [ ]:
import pandas as pd

data = {
    'Aluno': ['Ana', 'Bruno', 'Carlos', 'Ana', 'Daniela', 'Bruno', 'Carlos', 'Eduardo', 'Ana'],
    'Curso': ['Python Básico', 'Data Science', 'Machine Learning', 'Python Básico', 'Web Development', 'Data Science', 'Machine Learning', 'Design Gráfico', 'Python Básico'],
    'Data_Inscricao': ['2023-02-10', '2023-02-11', '2023-02-12', '2023-02-10', '2023-02-13', '2023-02-11', '2023-02-15', '2023-02-16', '2023-02-10'],
    'Valor_Pago': [100, 200, 250, 100, 150, 200, 250, 180, 100]  # Valores duplicados em algumas linhas
}

# transforma em DataFrame
df = pd.DataFrame(data)
display(df)

# separando as duplicatas:
duplicatas = df.duplicated()

# Mostra as duplicatas
print(f"Duplicatas localizadas: {duplicatas}")

df_unique = df.drop_duplicates(subset=['Aluno', 'Curso'], keep='first')

df_unique = df.drop_duplicates(subset=['Data_Inscricao', 'Valor_Pago'], keep='last')

df_unique = df_unique.reset_index(drop=True)

display(df_unique)